#!/bin/bash

git add .

# Get the current commit count
commit_count=$(git rev-list --count HEAD)

# Increment the commit count by 1
next_commit_count=$((commit_count + 1))

# Create a commit message with the incremented number
commit_message="Commit #$next_commit_count: 1 .. 1000"

# Commit with the generated message
git commit -m "$commit_message"

git push
